from __future__ import annotations

from pathlib import Path
import json
import shutil
import subprocess

from .models import Lab
from .amazon_scaffolds import ensure_amazon_repo_scaffold
from .lab_scaffolds import ensure_course_scaffold, course_lab_notes
from .js_react_scaffolds import ensure_js_react_scaffold


def ensure_lab_workspace(root: Path, lab: Lab) -> Path:
    target = root / lab.id
    target.mkdir(parents=True, exist_ok=True)

    if ensure_js_react_scaffold(target, lab):
        return target

    # Write the task-specific repository brief before the generic README. Each
    # scaffold writes only missing files, so the learner's edits remain intact.
    if lab.workspace_template in {"amazon_node", "amazon_cpp"}:
        ensure_amazon_repo_scaffold(target, lab)

    # Replace only guides generated by the former mock scaffold. Keep them as
    # archived copies so a learner's notes are never discarded.
    _preserve_legacy_guide(target / "README.md", ("Obiettivi Creativi & Bonus XP", "Angular Standalone Component simulato"))
    _preserve_legacy_guide(target / "SOLUTION.md", ("Angular Standalone reattiva guidata", "Bonus XP"))
    readme = target / "README.md"
    if not readme.exists():
        requirements = "\n".join(f"- [ ] {item}" for item in lab.requirements)
        rubric = "\n".join(f"- {item}" for item in lab.rubric)
        creative = ""
        if lab.creative_goals:
            creative = "\n\n## Estensioni facoltative\n" + "\n".join(f"- {item}" for item in lab.creative_goals)
        commands = {
            "amazon_node": "Esegui `npm test` da questa cartella; non servono pacchetti esterni.",
            "amazon_cpp": "Apri `CMakeLists.txt`; l'app compila ed esegue i test con GCC o Clang in C++20.",
            "dotnet": "Dalla cartella `server/` esegui `dotnet restore`, poi `dotnet test Tests/Server.Tests.csproj`. Per i progetti API avvia `dotnet run --urls http://localhost:5000`.",
            "angular": "Dalla cartella `client/` esegui `npm install`, poi `npm test`. Avvia la pagina con `npm start` e apri l'URL indicato nel terminale.",
            "monorepo": "In un terminale entra in `server/`, esegui `dotnet restore` e `dotnet run --urls http://localhost:5000`. In un secondo entra in `client/`, esegui `npm install` e `npm start`. Per i test usa `dotnet test Tests/Server.Tests.csproj` da `server/` e `npm test` da `client/`.",
        }.get(lab.workspace_template, "Per il server: `dotnet test Tests/Server.Tests.csproj`. Per Angular: `npm test`.")
        if lab.id == "lab-testing-xunit-vitest":
            commands = "Questo laboratorio verifica codice isolato: da `server/` esegui `dotnet test Tests/Server.Tests.csproj`; da `client/` esegui `npm install` e `npm test`. Per osservare il componente avvia `npm start` da `client/`."
        readme.write_text(
            f"# {lab.title}\n\n{lab.description}\n\n"
            "Questa cartella contiene un progetto iniziale da completare. I test automatici verificano soltanto i comportamenti coperti dalla suite; leggi i criteri e controlla anche i requisiti non verificati automaticamente.\n\n"
            "## Requisiti\n\n" f"{requirements}\n\n## Criteri di qualità\n\n{rubric}{creative}\n\n"
            "## Avvio e test\n\n"
            "Dopo ogni modifica, usa il pulsante **Esegui test** nell'app.\n\n"
            f"{commands}\n{course_lab_notes(lab)}",
            encoding="utf-8",
        )

    if lab.workspace_template in {"dotnet", "angular", "monorepo"}:
        solution = target / "SOLUTION.md"
        if not solution.exists():
            solution.write_text(
                f"# Guida di lavoro — {lab.title}\n\n"
                "Questa pagina non contiene la soluzione completa. Usala come mappa mentre implementi i requisiti.\n\n"
                "1. Leggi il README e individua un requisito verificabile alla volta.\n"
                "2. Avvia la suite corrispondente e annota il primo errore utile.\n"
                "3. Implementa il comportamento minimo, poi aggiungi un caso limite.\n"
                "4. Ripeti i test e confronta il risultato con i criteri di qualità.\n\n"
                "Un test verde è una prova circoscritta: non certifica da solo accessibilità, sicurezza, chiarezza o completezza del progetto.\n",
                encoding="utf-8",
            )

    if lab.workspace_template in {"amazon_node", "amazon_cpp"}:
        # The repository scaffold already supplies its own README, manifest,
        # source tree and tests. Do not append the generic solve(input) project
        # or its worked solution to an Amazon repository challenge.
        pass
    elif lab.workspace_template in {"dotnet", "angular", "monorepo"}:
        ensure_course_scaffold(target, lab)
    elif lab.workspace_template == "react":
        _ensure_react_project(target, lab)
    else:
        _ensure_plain_project(target, lab)

    return target


def _preserve_legacy_guide(path: Path, markers: tuple[str, ...]) -> None:
    if not path.is_file():
        return
    text = path.read_text(encoding="utf-8", errors="replace")
    if not any(marker in text for marker in markers):
        return
    destination = path.with_name(f"{path.stem}-legacy{path.suffix}")
    suffix = 2
    while destination.exists():
        destination = path.with_name(f"{path.stem}-legacy-{suffix}{path.suffix}")
        suffix += 1
    path.rename(destination)


def _ensure_plain_project(target: Path, lab: Lab) -> None:
    solution = target / "solution.js"
    if not solution.exists():
        solution.write_text(
            "// DEV//48 — descrivi prima input, output e casi limite.\n\nexport function solve(input) {\n  // TODO\n  return input;\n}\n",
            encoding="utf-8",
        )
    test = target / "solution.test.js"
    if not test.exists():
        test.write_text(
            "import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport { solve } from './solution.js';\n\ntest('gestisce una lista vuota', () => {\n  assert.deepEqual(solve([]), []);\n});\n\ntest('restituisce soltanto gli elementi attivi senza mutare input', () => {\n  const input = [{id:1, active:true}, {id:2, active:false}];\n  const snapshot = structuredClone(input);\n  assert.deepEqual(solve(input), [{id:1, active:true}]);\n  assert.deepEqual(input, snapshot);\n});\n",
            encoding="utf-8",
        )
    package = target / "package.json"
    if not package.exists():
        package.write_text(json.dumps({"type":"module","scripts":{"test":"node --test"}}, indent=2), encoding="utf-8")
    solution_guide = target / "SOLUTION.md"
    if not solution_guide.exists():
        solution_guide.write_text(
            "# Soluzione commentata\n\nAprila dopo almeno due tentativi reali.\n\n"
            "```js\nexport function solve(input) {\n  if (!Array.isArray(input)) throw new TypeError('input deve essere un array');\n  return input.filter(item => item.active === true);\n}\n```\n\n"
            "`filter` crea un nuovo array, quindi l'input non viene mutato. Il controllo iniziale rende esplicito il contratto della funzione. Aggiungeresti poi i requisiti specifici del brief mantenendo test piccoli e indipendenti.\n",
            encoding="utf-8",
        )


def _ensure_react_project(target: Path, lab: Lab) -> None:
    if not ensure_js_react_scaffold(target, lab):
        raise ValueError(f"Starter React non definito per {lab.id}")


def open_vscode(path: Path) -> tuple[bool, str]:
    code = shutil.which("code")
    if not code:
        return False, f"Il comando di VS Code non è disponibile. Apri questa cartella da VS Code: {path}"
    subprocess.Popen([code, str(path)], cwd=path)
    return True, f"Aperto in VS Code: {path}"


def install_lab_dependencies(path: Path) -> tuple[bool, str]:
    outputs = []
    success = True

    # Se c'è cartella server con .csproj/.sln, esegui dotnet restore
    if (path / "server").exists() or any(path.glob("*.csproj")) or any(path.glob("*.sln")):
        dotnet = shutil.which("dotnet")
        target_dir = path / "server" if (path / "server").exists() else path
        if dotnet:
            test_project = target_dir / "Tests" / "Server.Tests.csproj"
            restore_target = str(test_project) if test_project.is_file() else "."
            proc = subprocess.run([dotnet, "restore", restore_target], cwd=target_dir, capture_output=True, text=True, timeout=120, encoding="utf-8", errors="replace")
            outputs.append(f"[dotnet restore]\n{proc.stdout}\n{proc.stderr}")
            if proc.returncode != 0:
                success = False

    # Se c'è client con package.json o root con package.json, esegui npm install
    client_dir = path / "client" if (path / "client").exists() else path
    if (client_dir / "package.json").exists():
        npm = shutil.which("npm")
        if npm:
            try:
                package = json.loads((client_dir / "package.json").read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                package = {}
            if not package.get("dependencies") and not package.get("devDependencies"):
                outputs.append("[npm install]\nNessuna dipendenza esterna: il laboratorio funziona con Node.js e npm già installati.")
            else:
                proc = subprocess.run([npm, "install"], cwd=client_dir, capture_output=True, text=True, timeout=300, encoding="utf-8", errors="replace")
                outputs.append(f"[npm install]\n{proc.stdout}\n{proc.stderr}")
                if proc.returncode != 0:
                    success = False

    if (path / "CMakeLists.txt").is_file():
        compiler = next((shutil.which(name) for name in ("g++", "clang++") if shutil.which(name)), None)
        if compiler:
            outputs.append(f"[C++20]\nCompilatore trovato: {Path(compiler).name}.")
        else:
            outputs.append("[C++20]\nGCC/Clang non trovato nel PATH. Installa un compilatore C++20 per eseguire la suite.")
            success = False

    if not outputs:
        return False, "Non ho trovato un progetto .NET o Node da preparare in questa cartella."

    return success, ("\n\n".join(outputs))[-8000:]
