from __future__ import annotations

from pathlib import Path
import json
import shutil
import subprocess

from .models import Lab
from .lab_scaffolds import ensure_course_scaffold


def ensure_lab_workspace(root: Path, lab: Lab) -> Path:
    target = root / lab.id
    target.mkdir(parents=True, exist_ok=True)

    # Replace only guides generated by the former mock scaffold. Keep them as
    # archived copies so a learner's notes are never discarded.
    _preserve_legacy_guide(target / "README.md", ("Obiettivi Creativi & Bonus XP", "Angular Standalone Component simulato"))
    _preserve_legacy_guide(target / "SOLUTION.md", ("Angular Standalone reattiva guidata", "Bonus XP"))
    readme = target / "README.md"
    if not readme.exists():
        requirements = "\n".join(f"- [ ] {item}" for item in lab.requirements)
        rubric = "\n".join(f"- {item}" for item in lab.rubric)
        creative = ""
        if lab.creative_goals:
            creative = "\n\n## Estensioni facoltative\n" + "\n".join(f"- {item}" for item in lab.creative_goals)
        readme.write_text(
            f"# {lab.title}\n\n{lab.description}\n\n"
            "Questo workspace contiene uno starter da completare. I test automatici verificano soltanto i comportamenti dichiarati dai test presenti; leggi anche i criteri e controlla manualmente i requisiti che non sono coperti.\n\n"
            "## Requisiti\n\n" f"{requirements}\n\n## Criteri di qualità\n\n{rubric}{creative}\n\n"
            "## Avvio e test\n\n"
            "Installa le dipendenze dal pulsante **Installa dipendenze** nell'app. Poi usa **Esegui test**.\n"
            "Per il server: `dotnet test Tests/Server.Tests.csproj`. Per Angular: `npm test`.\n",
            encoding="utf-8",
        )

    if lab.workspace_template in {"dotnet", "angular", "monorepo"}:
        solution = target / "SOLUTION.md"
        if not solution.exists():
            solution.write_text(
                f"# Guida di lavoro — {lab.title}\n\n"
                "Questa pagina non contiene la soluzione completa. Usala come mappa mentre implementi i requisiti.\n\n"
                "1. Leggi il README e individua un requisito verificabile alla volta.\n"
                "2. Avvia la suite corrispondente e annota il primo errore utile.\n"
                "3. Implementa il comportamento minimo, poi aggiungi un caso limite.\n"
                "4. Ripeti i test e confronta il risultato con i criteri di qualità.\n\n"
                "Un test verde è una prova circoscritta: non certifica da solo accessibilità, sicurezza, chiarezza o completezza del progetto.\n",
                encoding="utf-8",
            )

    if lab.workspace_template in {"dotnet", "angular", "monorepo"}:
        ensure_course_scaffold(target, lab)
    elif lab.workspace_template == "react":
        _ensure_react_project(target, lab)
    else:
        _ensure_plain_project(target, lab)

    return target


def _preserve_legacy_guide(path: Path, markers: tuple[str, ...]) -> None:
    if not path.is_file():
        return
    text = path.read_text(encoding="utf-8", errors="replace")
    if not any(marker in text for marker in markers):
        return
    destination = path.with_name(f"{path.stem}-legacy{path.suffix}")
    suffix = 2
    while destination.exists():
        destination = path.with_name(f"{path.stem}-legacy-{suffix}{path.suffix}")
        suffix += 1
    path.rename(destination)


def _ensure_plain_project(target: Path, lab: Lab) -> None:
    solution = target / "solution.js"
    if not solution.exists():
        solution.write_text(
            "// DEV//48 — descrivi prima input, output e casi limite.\n\nexport function solve(input) {\n  // TODO\n  return input;\n}\n",
            encoding="utf-8",
        )
    test = target / "solution.test.js"
    if not test.exists():
        test.write_text(
            "import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport { solve } from './solution.js';\n\ntest('gestisce una lista vuota', () => {\n  assert.deepEqual(solve([]), []);\n});\n\ntest('restituisce soltanto gli elementi attivi senza mutare input', () => {\n  const input = [{id:1, active:true}, {id:2, active:false}];\n  const snapshot = structuredClone(input);\n  assert.deepEqual(solve(input), [{id:1, active:true}]);\n  assert.deepEqual(input, snapshot);\n});\n",
            encoding="utf-8",
        )
    package = target / "package.json"
    if not package.exists():
        package.write_text(json.dumps({"type":"module","scripts":{"test":"node --test"}}, indent=2), encoding="utf-8")
    solution_guide = target / "SOLUTION.md"
    if not solution_guide.exists():
        solution_guide.write_text(
            "# Soluzione commentata\n\nAprila dopo almeno due tentativi reali.\n\n"
            "```js\nexport function solve(input) {\n  if (!Array.isArray(input)) throw new TypeError('input deve essere un array');\n  return input.filter(item => item.active === true);\n}\n```\n\n"
            "`filter` crea un nuovo array, quindi l'input non viene mutato. Il controllo iniziale rende esplicito il contratto della funzione. Aggiungeresti poi i requisiti specifici del brief mantenendo test piccoli e indipendenti.\n",
            encoding="utf-8",
        )


def _ensure_react_project(target: Path, lab: Lab) -> None:
    files = {
        "package.json": json.dumps({
            "name": lab.id, "private": True, "version": "1.0.0", "type": "module",
            "scripts": {"dev":"vite", "test":"vitest", "build":"vite build"},
            "dependencies": {"react":"19.2.8", "react-dom":"19.2.8"},
            "devDependencies": {"@vitejs/plugin-react":"6.0.5", "vite":"8.2.1", "vitest":"4.1.10", "jsdom":"29.1.1", "@testing-library/react":"16.3.2", "@testing-library/jest-dom":"7.0.0"},
        }, indent=2),
        "index.html": '<!doctype html><html lang="it"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DEV48 Lab</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>',
        "vite.config.js": "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nexport default defineConfig({ plugins:[react()], test:{ environment:'jsdom', globals:true, setupFiles:'./src/testSetup.js' } });\n",
        "src/main.jsx": "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App.jsx';\nimport './styles.css';\ncreateRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);\n",
        "src/App.jsx": """import { useMemo, useState } from 'react';

const initialSubjects = [
  { id: 1, name: 'Mario Rossi', zone: 'Centro', active: true },
  { id: 2, name: 'Anna Bianchi', zone: 'Nord', active: false },
];

export default function App() {
  const [subjects, setSubjects] = useState(initialSubjects);
  const [query, setQuery] = useState('');
  const visibleSubjects = useMemo(
    () => subjects.filter(subject => subject.name.toLowerCase().includes(query.toLowerCase())),
    [subjects, query],
  );

  function removeSubject(id) {
    // TODO: implementazione immutabile
  }

  return (
    <main className="page">
      <h1>Archivio soggetti</h1>
      <label htmlFor="search">Cerca</label>
      <input id="search" value={query} onChange={event => setQuery(event.target.value)} />
      <p>{visibleSubjects.length} risultati</p>
      <ul>
        {visibleSubjects.map(subject => (
          <li key={subject.id}>
            <span>{subject.name}</span>
            <button onClick={() => removeSubject(subject.id)}>Elimina</button>
          </li>
        ))}
      </ul>
    </main>
  );
}
""",
        "src/styles.css": """:root{font-family:Inter,system-ui;background:#0b1020;color:#e7eefc}*{box-sizing:border-box}.page{width:min(100% - 2rem,60rem);margin:3rem auto;padding:2rem;background:#131b2f;border:1px solid #283654;border-radius:18px}input{display:block;width:100%;margin:.5rem 0 1rem;padding:.8rem;background:#0b1020;color:inherit;border:1px solid #3b4e75;border-radius:8px}li{display:flex;justify-content:space-between;padding:1rem;border-bottom:1px solid #283654}button{background:#8b5cf6;color:white;border:0;padding:.55rem .9rem;border-radius:8px}""",
        "src/testSetup.js": "import '@testing-library/jest-dom/vitest';\n",
        "src/App.test.jsx": """import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import App from './App.jsx';

describe('DEV48 lab', () => {
  it('filters subjects', () => {
    render(<App />);
    fireEvent.change(screen.getByLabelText('Cerca'), { target: { value: 'Anna' } });
    expect(screen.getByText('Anna Bianchi')).toBeInTheDocument();
    expect(screen.queryByText('Mario Rossi')).not.toBeInTheDocument();
  });

  it('removes a subject', () => {
    render(<App />);
    const buttons = screen.getAllByRole('button', { name: 'Elimina' });
    fireEvent.click(buttons[0]);
    expect(screen.queryByText('Mario Rossi')).not.toBeInTheDocument();
  });
});
""",
    }
    for relative, content in files.items():
        path = target / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(content, encoding="utf-8")
    solution_guide = target / "SOLUTION.md"
    if not solution_guide.exists():
        solution_guide.write_text(
            "# Soluzione commentata\n\nAprila dopo almeno due tentativi reali.\n\n"
            "La parte minima che completa lo starter è:\n\n"
            "```jsx\nfunction removeSubject(id) {\n  setSubjects(current => current.filter(subject => subject.id !== id));\n}\n```\n\n"
            "L'updater funzionale usa sempre lo stato più recente. `filter` restituisce un nuovo array e conserva l'immutabilità richiesta da React. Dopo aver ottenuto i test verdi, estendi il progetto seguendo il brief e aggiungi test per lista vuota, input non valido ed errore API.\n",
            encoding="utf-8",
        )


def open_vscode(path: Path) -> tuple[bool, str]:
    code = shutil.which("code")
    if not code:
        return False, f"VS Code CLI non trovato. Apri manualmente: {path}"
    subprocess.Popen([code, str(path)], cwd=path)
    return True, f"Aperto in VS Code: {path}"


def install_lab_dependencies(path: Path) -> tuple[bool, str]:
    outputs = []
    success = True

    # Se c'è cartella server con .csproj/.sln, esegui dotnet restore
    if (path / "server").exists() or any(path.glob("*.csproj")) or any(path.glob("*.sln")):
        dotnet = shutil.which("dotnet")
        target_dir = path / "server" if (path / "server").exists() else path
        if dotnet:
            test_project = target_dir / "Tests" / "Server.Tests.csproj"
            restore_target = str(test_project) if test_project.is_file() else "."
            proc = subprocess.run([dotnet, "restore", restore_target], cwd=target_dir, capture_output=True, text=True, timeout=120, encoding="utf-8", errors="replace")
            outputs.append(f"[dotnet restore]\n{proc.stdout}\n{proc.stderr}")
            if proc.returncode != 0:
                success = False

    # Se c'è client con package.json o root con package.json, esegui npm install
    client_dir = path / "client" if (path / "client").exists() else path
    if (client_dir / "package.json").exists():
        npm = shutil.which("npm")
        if npm:
            proc = subprocess.run([npm, "install"], cwd=client_dir, capture_output=True, text=True, timeout=300, encoding="utf-8", errors="replace")
            outputs.append(f"[npm install]\n{proc.stdout}\n{proc.stderr}")
            if proc.returncode != 0:
                success = False

    if not outputs:
        return False, "Nessun gestore dipendenze rilevato (né dotnet né npm)."

    return success, ("\n\n".join(outputs))[-8000:]
