"""Editorial contracts for the existing twelve JavaScript/React laboratories."""

LAB_BRIEFS = {
    "lab-js-crud": [
        "Implementa addSubject, updateSubject, removeSubject, searchSubjects e summarizeSubjects in solution.mjs.",
        "Conserva l'input e i campi non aggiornati; gli ID restano stabili e l'aggiunta rifiuta un ID duplicato.",
        "La ricerca ignora maiuscole e spazi esterni; [] produce una lista vuota e un riepilogo con totali zero.",
        "Prima di guardare la soluzione, aggiungi un caso in cui modifica, filtro e riepilogo lavorano sullo stesso dataset.",
    ],
    "lab-js-debug": [
        "Ripara le sei funzioni già presenti in solution.mjs, partendo dall'errore osservato nei test.",
        "Individua la causa per confronti, return delle callback, copie annidate, ricerca per ID, aggregazione e validazione.",
        "Per ogni bug annota input minimo, risultato atteso e correzione; evita di sostituire tutte le funzioni insieme.",
        "Conserva l'input originale e verifica anche zero, assenze e collezioni vuote.",
    ],
    "lab-html-dashboard": [
        "Completa index.html e styles.css: main, gerarchia h1/h2, navigazione, ricerca con label e card dei soggetti.",
        "Costruisci layout fluido con una colonna iniziale e più colonne quando il contenuto ha spazio.",
        "Usa pulsanti per azioni e link per navigazione; rendi visibile il focus e associa il testo d'aiuto al campo.",
        "I test controllano soltanto struttura e regole: nel browser verifica Tab, 320px, 768px, testo lungo e zoom 200%.",
    ],
    "lab-fetch": [
        "Implementa createClient(request) con load(url), getState() e cancel() in solution.mjs.",
        "Lo stato distingue idle, loading, success, empty ed error; una nuova load dopo un errore costituisce il retry.",
        "Controlla status HTTP, JSON e forma dei dati; [] è un successo vuoto, non un errore.",
        "Una richiesta precedente non può sovrascrivere l'ultima, anche se il trasporto ignora AbortController.",
        "Questo lab testa il modello asincrono senza UI né rete; il collegamento ai messaggi visibili avviene in lab-react-api.",
    ],
    "lab-react-list": [
        "Completa App.jsx: ricerca controllata, lista derivata, conteggio ed eliminazione per ID senza mutare i dati iniziali.",
        "La ricerca ignora maiuscole e spazi esterni; distingui nessuna corrispondenza da archivio completamente vuoto.",
        "Dopo un'eliminazione aggiorna lista e conteggio anche con filtro attivo; conserva la ricerca.",
        "Non duplicare visible nello stato e non aggiungere useMemo senza una misura che lo giustifichi.",
        "I test renderizzano React in jsdom; controlla anche tastiera e focus nel browser.",
    ],
    "lab-ts-model": [
        "Completa model.ts con Subject, LoadResult, isSubject e describeResult.",
        "Il guard rifiuta null, array e proprietà di tipo errato; la union distingue success, empty ed error.",
        "Evita any e cast per nascondere dati invalidi; la nota del soggetto è facoltativa.",
        "Node esegue il codice rimuovendo i tipi: i test provano i rami e la validazione a runtime, non sostituiscono tsc.",
    ],
    "lab-react-form": [
        "Implementa creazione e modifica del nome con input controllato, submit e pulsante Annulla modifica.",
        "Rifiuta il nome vuoto o fatto di spazi; collega errore e label al campo e conserva il testo invalido.",
        "La creazione genera un ID stabile; la modifica conserva l'ID e i campi non modificati.",
        "L'annullamento non modifica il record; un successo normalizza il nome e azzera il form.",
        "Verifica submit da tastiera e correzione dopo un errore; i test DOM non certificano l'accessibilità completa.",
    ],
    "lab-react-api": [
        "Integra caricamento, creazione, modifica ed eliminazione con il contratto API locale in server.mjs.",
        "Mostra loading, error, empty, success e Riprova; non sovrascrivere dati con risultati fuori ordine.",
        "Valida il nome e impedisci invii duplicati mentre il salvataggio è in corso.",
        "Su errore di salvataggio conserva nome e dati correnti; azzera il form soltanto dopo il successo.",
        "I test separano UI con API controllata e contratto HTTP locale; nel browser avvia API e Vite e prova il flusso completo.",
        "Approfondimento dopo i test verdi: aggiornamento ottimistico con ripristino esplicito su fallimento.",
    ],
    "lab-sql": [
        "Completa schema.sql e queries.sql per soggetti, misure e controlli con chiavi, riferimenti e vincoli.",
        "Scrivi ricerca ordinata dei soggetti attivi e LEFT JOIN che conserva chi non ha misure.",
        "Implementa removeSubject(db, id) in solution.mjs come transazione: elimina record collegati e soggetto insieme.",
        "Un fallimento deve ripristinare tutti i dati; verifica ID assente e violazioni dei vincoli.",
        "La suite usa SQLite reale integrato in Node; motiva un indice in base a una query, senza indicizzare ogni colonna.",
    ],
    "lab-git": [
        "Esegui node setup.mjs per creare la repository didattica locale repo/, separata dalla repository DEV48.",
        "Esamina i due branch, unisci feature-search in main e risolvi il conflitto conservando entrambe le modifiche richieste.",
        "Controlla git diff e git diff --staged prima di registrare il risultato; non sono previste operazioni remote.",
        "I test verificano contenuto, assenza di conflitti, branch corrente e working tree pulito; spiega anche la scelta della risoluzione.",
    ],
    "lab-debug-app": [
        "Diagnostica i difetti tra repository.mjs, service.mjs e format.mjs tramite i test di integrazione.",
        "Correggi ricerca, aggiornamento, filtro e gestione dell'assenza conservando gli input e le altre righe.",
        "Per ogni correzione indica il test che falliva e aggiungi una regressione utile prima di passare al difetto successivo.",
        "Il lab esegue la logica Node; non considera un log o la presenza di un nome come prova di correttezza.",
    ],
    "lab-final": [
        "Costruisci il mini gestionale usando il contratto API e i test forniti: lista, ricerca, form, modifica ed eliminazione.",
        "Decidi autonomamente la divisione dei componenti e il proprietario dello stato; motiva la scelta nel README.",
        "Verifica riepilogo dei risultati, richieste fuori ordine, errore recuperabile e conservazione dei dati su fallimento.",
        "Nel browser usa API e Vite, ricarica la pagina per controllare la persistenza durante la vita del server e prova la tastiera.",
        "Documenta comandi, limiti del server didattico e casi non coperti; auth, deployment e dati reali sono fuori da questo laboratorio.",
    ],
}

PRACTICE_SCENARIOS = {
    "SELECT, filtri e ordinamento": "Scrivi una query che restituisca id, name e checks dei soli soggetti attivi, ordinati per checks decrescente. Prevedi le righe prima di eseguirla e spiega perché l'ordine deve essere esplicito.",
    "Relazioni e JOIN": "Scrivi una LEFT JOIN che conservi anche il soggetto senza misure. Confronta il risultato con INNER JOIN: quale riga scompare e quale campo è NULL? Controlla il caso prima di aggiungere filtri.",
    "HTTP e API REST": "L'API ha creato il soggetto 42. Scrivi un esempio di risposta con status e Location e spiega come la distingui da input invalido e risorsa assente.",
    "Autenticazione, CORS e segreti": "Un client da terminale chiama l'API anche se l'origine non è ammessa dal browser. Spiega perché CORS non blocca quel client e quali controlli devono rimanere sul server. Usa un esempio di permesso negato.",
    "Node, event loop e moduli": "Un endpoint esegue per tre secondi un calcolo sincrono; nello stesso processo un altro client chiede una lista piccola. Prevedi il ritardo e spiega perché aggiungere async al nome della funzione non rende parallelo il calcolo.",
    "Route, middleware e validazione": "Per POST /subjects disegna il percorso da JSON non valido a risposta 400, poi quello da input valido a risposta 201. Indica quale parte valida, quale salva e quale traduce un errore del servizio.",
    "Sicurezza web essenziale": "Un nome contiene un apostrofo. Confronta concatenazione SQL e parametro: mostra dove viene inserito il valore e spiega quale difesa manca ancora se il chiamante non ha il permesso di leggere il record.",
    "Vincoli, indici e normalizzazione": "La query frequente cerca gli attivi di una zona. Proponi un indice e descrivi la lettura che può aiutare e la scrittura che deve mantenerlo. Nel lab-sql verifica anche un vincolo con un INSERT invalido.",
    "Transazioni e concorrenza": "Nel lab-sql elimina un soggetto con record collegati e provoca un errore dopo il primo DELETE. Prima di eseguire, scrivi quali dati devono rimanere dopo il rollback e perché un commit parziale sarebbe scorretto.",
    "Git: working tree, staging e commit": "Modifichi due righe, aggiungi il file allo staging e modifichi una terza riga. Prevedi cosa mostrano git diff e git diff --staged e quale contenuto entrerà nel commit. Verifica in una repository didattica separata.",
    "Branch, merge e conflitti": "Due branch cambiano la stessa riga con requisiti entrambi validi. Descrivi come conservare le due intenzioni, controllare HEAD e verificare il risultato prima di registrare la risoluzione nel laboratorio Git.",
    "Test unitari, integrazione ed E2E": "La validazione del nome passa, ma il pulsante Salva non aggiorna la lista. Scegli il livello di test che scopre il collegamento mancante; scrivi azione e risultato atteso senza riferirti al nome di un hook.",
    "Code review e refactoring": "Vuoi estrarre la ricerca da un componente che mostra anche form e lista. Definisci prima i casi da preservare, poi una singola estrazione e una prova di regressione. Distingui il refactoring da un cambio del requisito.",
    "PHP e ciclo di un plugin WordPress": "Un plugin deve cambiare il titolo di una pagina senza modificare il core. Scegli action o filter e mostra un frammento che restituisce il valore trasformato; spiega l'errore di dimenticare return.",
    "Sicurezza WordPress": "Un form riceve un nome e aggiorna una voce amministrativa. Indica dove sanitizzi, dove fai escaping e dove verifichi capability e nonce. Spiega perché un nonce valido non basta ad autorizzare la modifica.",
    "Presentare l'architettura di un'app Electron": "Una vista React deve leggere un soggetto dal database. Disegna renderer → preload → IPC → main e indica quale API ristretta esporresti. Motiva la validazione dell'ID nel processo privilegiato.",
    "Presentare una pipeline AI multimodale": "La risposta testuale è pronta, ma TTS non risponde. Disegna il recupero che conserva il testo e permette retry audio, evitando di associarlo a una richiesta successiva. Non serve implementare nuovi servizi.",
    "Parlare onestamente dell'uso dell'IA": "Scegli una funzione del lab-js-crud e ricostruiscila senza leggere la soluzione. Confronta il risultato con i test e annota quale parte sai spiegare e quale richiede ancora ripasso. Riporta un esempio concreto.",
    "Comunicare decisioni tecniche e risultati": "Usa un bug trovato nel laboratorio e scrivi un breve resoconto: input, sintomo, ipotesi, correzione e test che la verifica. Conserva un esempio riproducibile al posto di un elenco di tecnologie.",
}
